### ISSUE TITLE
adding functions for Perlin noise

### ISSUE THREAD

**Issue by manas271196** [d3/d3-random#20]
Would there be a use case for a Perlin noise function in this module? I can see two functions: perlin2d and perlin3d as useful in creating random but continuous distributions. One use case would be to return a single noise value. Other use cases I can think of are to return an array of noise depending on the given interval. May also be useful in using with d3.contour for procedural generation of contours.

If you guys think this may be useful, I have been working something and could send a PR.

**Comment by mbostock** [comment]
Seems like there are already some libraries available that do this? E.g., https://github.com/josephg/noisejs Maybe a standalone library would be best if you find the existing libraries insufficient?

**Comment by manas271196** [comment]
Yeah, I was just wondering if adding it to D3 itself would be useful. But yeah you're right, nothing completely new I can think of to do with Perlin.

**Comment by manas271196** [comment]
Closing

**Comment by mbostock** [comment]
A demo of 2D Perlin noise and d3-contour would make a nice example to link from the README!
