### ISSUE TITLE
randomInt(): reason for flooring interval end-points?

### ISSUE THREAD

**Issue by sabu36** [d3/d3-random#38]
When placing a Go stone in each quadrant, we get a pair of intervals:
0 <= coordinate < 9.5
9.5 <= coordinate < 19

Currently, `randomInt(0, 9.5)` is equivalent to `randomInt(0, 9)`, making it unsuitable.

Now, it's not difficult to do it with `randomUniform()` but I wondered why the parameters `min` and `max` are floored individually instead of only the result of calculation.

**Comment by mbostock** [comment]
randomInt only returns integers, and each possible integer is intended to be returned with equal (uniform) probability. I agree we *could* have done it the way you describe to allow a different (lesser) probability for the minimum or maximum integer, but that feels like an edge case and you’re probably better off using randomUniform for that.
