### ISSUE TITLE
Should this module be exhaustive for statistical distributions?

### ISSUE THREAD

**Issue by p-v-d-Veeken** [d3/d3-random#7]
Hi, 

I was wondering what exactly the intended direction for this D3 module is? With which I mean, is it supposed to be used to model/simulate all kinds of statistical processes and events? if so shouldn't it also include more frequently used distributions, such as Bernoulli, Bionomial, Geometric, Pareto, to name a few? 

I would gladly implement a few of these distributions and create a pull request, however I thought I'd ask first, to make sure I wouldn't be wasting my time.

Cheers!

**Comment by mikroware** [comment]
:+1:

**Comment by mbostock** [comment]
I don’t have a strong opinion on the direction of this module. So far, I’ve just included a handful of random number generators that were useful to me in the past. I think it would be nice to have additional ones here, provided they are written in a consistent style to the current ones.

**Comment by wassname** [comment]
I just searched for the best way to generate random numbers on a distribution in JS and came to this library. So I suggest this could become *the* js library for generating numbers on random distributions. 

It seems like something that JS needs, and the only change you really need is a snazzy name like abnormal, slapdash, or rand3m. That's just so it looks like a standalone module at first glance.

Just my 2c, and thanks for making this library.

**Comment by mbostock** [comment]
I merged #14 and it’ll be available in the next release of d3-random. I’m hesitant to say this module should be “exhaustive” because it is included with the default bundle of D3, and I’d like to keep the bundle relatively small. But if the implementation is simple and the distributions are commonly-needed, we should add them.

(Sorry for the delayed response!)
